# Generated by Django 4.0.1 on 2022-01-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDHARules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_section_title', models.CharField(max_length=255)),
                ('rule_subsection_num', models.CharField(max_length=1)),
                ('rule_subsection_title', models.CharField(max_length=255)),
                ('rule_details', models.CharField(max_length=3000)),
            ],
        ),
    ]
