# Generated by Django 4.0.1 on 2022-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edharules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edharules',
            name='rule_subsection_num',
            field=models.CharField(max_length=2),
        ),
    ]
